# Generated by Django 2.1.5 on 2019-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(blank=True, upload_to='profilepics'),
        ),
    ]
