# Generated by Django 2.1.5 on 2019-02-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190207_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='profilepics'),
        ),
    ]
